#include <pci/desktop/viewport/RenderMetricsProjection.h>

namespace pci {

RenderMetrics projectRenderMetrics(const RenderTelemetrySnapshot &telemetry)
{
    return {
        .deviceName = QString::fromStdString(telemetry.backend.deviceName),
        .requestedBackend =
            QString::fromStdString(telemetry.backend.requestedBackend),
        .selectedBackend =
            QString::fromStdString(telemetry.backend.selectedBackend),
        .timingSource = QString::fromStdString(telemetry.backend.timingSource),
        .gpuValidationEnabled = telemetry.backend.gpuValidationEnabled,
        .framesPerSecond = telemetry.frame.framesPerSecond,
        .frameMilliseconds = telemetry.frame.frameMilliseconds,
        .sampledFrameMilliseconds = telemetry.frame.sampledFrameMilliseconds,
        .outputWidth = telemetry.frame.outputWidth,
        .outputHeight = telemetry.frame.outputHeight,
        .qualificationPhase = {},
        .qualificationFrameIndex = 0,
        .qualificationFrameCount = 0,
        .qualificationFrame = false,
        .qualificationFinalFrame = false,
        .requestedPoints = telemetry.selection.requestedPoints,
        .selectedPoints = telemetry.selection.selectedPoints,
        .submittedPoints = telemetry.selection.submittedPoints,
        .drawCalls = telemetry.selection.drawCalls,
        .vectorLayersDrawn = telemetry.selection.vectorLayersDrawn,
        .vectorDrawCalls = telemetry.selection.vectorDrawCalls,
        .gpuVectorBytes = telemetry.residency.gpuVectorBytes,
        .rasterCpuBytes = telemetry.residency.rasterCpuBytes,
        .rasterCpuBudgetBytes = telemetry.residency.rasterCpuBudgetBytes,
        .rasterCpuPeakBytes = telemetry.residency.rasterCpuPeakBytes,
        .rasterGpuBytes = telemetry.residency.rasterGpuBytes,
        .rasterHeightGpuBytes = telemetry.residency.rasterHeightGpuBytes,
        .rasterGpuBudgetBytes = telemetry.residency.rasterGpuBudgetBytes,
        .rasterGpuPeakBytes = telemetry.residency.rasterGpuPeakBytes,
        .rasterTilesRequested = telemetry.residency.rasterTilesRequested,
        .rasterTilesCompleted = telemetry.residency.rasterTilesCompleted,
        .rasterTilesCancelled = telemetry.residency.rasterTilesCancelled,
        .rasterTilesFailed = telemetry.residency.rasterTilesFailed,
        .rasterCacheEvictions = telemetry.residency.rasterCacheEvictions,
        .rasterUploadedTiles = telemetry.residency.rasterUploadedTiles,
        .rasterResidentTiles = telemetry.residency.rasterResidentTiles,
        .rasterSelectedTiles = telemetry.residency.rasterSelectedTiles,
        .rasterDrawnTiles = telemetry.residency.rasterDrawnTiles,
        .rasterSurfaceDrawnTiles = telemetry.residency.rasterSurfaceDrawnTiles,
        .rasterSurfaceTriangles = telemetry.residency.rasterSurfaceTriangles,
        .rasterPendingReads = telemetry.residency.rasterPendingReads,
        .rasterFinestLevel = telemetry.residency.rasterFinestLevel,
        .rasterCoarsestLevel = telemetry.residency.rasterCoarsestLevel,
        .rasterCoverageIncomplete =
            telemetry.residency.rasterCoverageIncomplete,
        .submittedFrameCount = telemetry.frame.submittedFrameCount,
        .sourcePoints = telemetry.selection.sourcePoints,
        .retainedFlatPoints = telemetry.selection.retainedFlatPoints,
        .decodedResidentPoints = telemetry.decode.decodedResidentPoints,
        .gpuResidentPoints = telemetry.residency.gpuResidentPoints,
        .visibleBlocks = telemetry.selection.visibleBlocks,
        .culledBlocks = telemetry.selection.culledBlocks,
        .framePlanReused = telemetry.selection.framePlanReused,
        .uniformDrawCapacity = telemetry.upload.uniformDrawCapacity,
        .uniformCapacityGrowthCount =
            telemetry.upload.uniformCapacityGrowthCount,
        .uniformUpdateOperations = telemetry.upload.uniformUpdateOperations,
        .uploadedPointBytes = telemetry.upload.uploadedPointBytes,
        .protectedGpuPointBytes = telemetry.upload.protectedGpuPointBytes,
        .pendingUploadBytes = telemetry.upload.pendingUploadBytes,
        .uploadOperations = telemetry.upload.uploadOperations,
        .uploadResourceUpdateBatches = telemetry.upload.resourceUpdateBatches,
        .sceneSnapshotMilliseconds = telemetry.frame.sceneSnapshotMilliseconds,
        .selectionMilliseconds = telemetry.frame.selectionMilliseconds,
        .uploadMilliseconds = telemetry.frame.uploadMilliseconds,
        .commandRecordingMilliseconds =
            telemetry.frame.commandRecordingMilliseconds,
        .frameIncludedUploads = telemetry.frame.includedUploads,
        .frameIncludedPick = telemetry.frame.includedPick,
        .pickInputBlocks = telemetry.picking.inputBlocks,
        .pickCandidateBlocks = telemetry.picking.candidateBlocks,
        .pickInputPoints = telemetry.picking.inputPoints,
        .pickCandidatePoints = telemetry.picking.candidatePoints,
        .lodRefinePixelError = telemetry.selection.lodRefinePixelError,
        .gpuPointBudgetBytes = telemetry.residency.gpuPointBudgetBytes,
        .decodedPointBytes = telemetry.decode.decodedPointBytes,
        .retainedFlatBytes = telemetry.decode.retainedFlatBytes,
        .decodedPointBudgetBytes = telemetry.decode.decodedPointBudgetBytes,
        .peakDecodedPointBytes = telemetry.decode.peakDecodedPointBytes,
        .gpuPointBytes = telemetry.residency.gpuPointBytes,
        .peakGpuPointBytes = telemetry.residency.peakGpuPointBytes,
        .gpuCacheEvictions = telemetry.residency.gpuCacheEvictions,
        .cacheHits = telemetry.decode.cacheHits,
        .cacheMisses = telemetry.decode.cacheMisses,
        .cacheEvictions = telemetry.decode.cacheEvictions,
        .sourceRequests = telemetry.decode.sourceRequests,
        .sourceRequestsCompleted = telemetry.decode.sourceRequestsCompleted,
        .sourceRequestsCancelled = telemetry.decode.sourceRequestsCancelled,
        .sourceRequestsFailed = telemetry.decode.sourceRequestsFailed,
        .estimatedSourceBytesRequested =
            telemetry.decode.estimatedSourceBytesRequested,
        .decodedSourceBytesProduced =
            telemetry.decode.decodedSourceBytesProduced,
        .decodeRequestsQueued = telemetry.decode.decodeRequestsQueued,
        .decodeRequestsStarted = telemetry.decode.decodeRequestsStarted,
        .decodeRequestsCompleted = telemetry.decode.decodeRequestsCompleted,
        .decodeRequestsCancelled = telemetry.decode.decodeRequestsCancelled,
        .decodeRequestsFailed = telemetry.decode.decodeRequestsFailed,
        .activeDecoderEstimatedBytes =
            telemetry.decode.activeDecoderEstimatedBytes,
        .peakDecoderEstimatedBytes = telemetry.decode.peakDecoderEstimatedBytes,
        .activeDecodes = telemetry.decode.activeDecodes,
        .pendingDecodes = telemetry.decode.pendingDecodes,
        .persistentIndexBytes = telemetry.decode.persistentIndexBytes,
        .localPersistentSources = telemetry.decode.localPersistentSources,
        .reusedPersistentSources = telemetry.decode.reusedPersistentSources,
        .visibleLayerCount = telemetry.selection.visibleLayerCount,
        .coveredLayerCount = telemetry.selection.coveredLayerCount,
        .rootOnlyLayerCount = telemetry.selection.rootOnlyLayerCount,
        .processResidentBytes = telemetry.residency.processResidentBytes,
        .peakProcessResidentBytes =
            telemetry.residency.peakProcessResidentBytes,
    };
}

} // namespace pci
