include_guard(GLOBAL)

function(pci_normalize_link_item output item)
    set(normalized "${item}")
    if(normalized MATCHES "^\\$<LINK_ONLY:(.*)>$")
        set(normalized "${CMAKE_MATCH_1}")
    endif()
    if(TARGET "${normalized}")
        get_target_property(aliased_target "${normalized}" ALIASED_TARGET)
        if(aliased_target)
            set(normalized "${aliased_target}")
        endif()
    endif()
    set(${output} "${normalized}" PARENT_SCOPE)
endfunction()

function(pci_register_architecture_checks)
    set(target_names
        pcinspector_foundation
        pcinspector_platform
        pcinspector_navigation
        pcinspector_pointcloud
        pcinspector_raster
        pcinspector_vector
        pcinspector_tasking
        pcinspector_scene
        pcinspector_development_support
        pcinspector_import_api
        pcinspector_renderer_api
        pcinspector_renderer_planning
        pcinspector_app_config
        pcinspector_app_model
        pcinspector_app_session
        pcinspector_import_pdal
        pcinspector_gdal_runtime
        pcinspector_import_gdal
        pcinspector_import_ogr
        pcinspector_import_async
        pcinspector_app_ui
        pcinspector_renderer
        pcinspector)

    set(allowed_pcinspector_foundation "")
    set(allowed_pcinspector_platform pcinspector_foundation Psapi)
    set(allowed_pcinspector_navigation pcinspector_foundation)
    set(allowed_pcinspector_pointcloud pcinspector_foundation)
    set(allowed_pcinspector_raster
        pcinspector_foundation pcinspector_pointcloud)
    set(allowed_pcinspector_vector
        pcinspector_earcut pcinspector_foundation)
    set(allowed_pcinspector_tasking pcinspector_foundation)
    set(allowed_pcinspector_scene
        pcinspector_foundation
        pcinspector_pointcloud
        pcinspector_raster
        pcinspector_tasking
        pcinspector_vector)
    set(allowed_pcinspector_development_support
        pcinspector_pointcloud pcinspector_scene)
    set(allowed_pcinspector_import_api pcinspector_scene)
    set(allowed_pcinspector_renderer_api pcinspector_scene Qt6::Core)
    set(allowed_pcinspector_renderer_planning
        pcinspector_foundation pcinspector_pointcloud pcinspector_scene)
    set(allowed_pcinspector_app_config
        pcinspector_foundation
        pcinspector_platform
        pcinspector_renderer_api)
    set(allowed_pcinspector_app_model
        pcinspector_import_api pcinspector_renderer_api)
    set(allowed_pcinspector_app_session
        pcinspector_app_config
        pcinspector_app_model
        pcinspector_import_async
        pcinspector_platform
        pcinspector_scene
        Qt6::Core)
    set(allowed_pcinspector_import_pdal
        pcinspector_import_api PDAL::pdalcpp Qt6::Core)
    set(allowed_pcinspector_gdal_runtime GDAL::GDAL)
    set(allowed_pcinspector_import_gdal
        pcinspector_gdal_runtime pcinspector_raster)
    set(allowed_pcinspector_import_ogr
        pcinspector_gdal_runtime pcinspector_vector)
    set(allowed_pcinspector_import_async
        pcinspector_import_api
        pcinspector_platform
        pcinspector_raster
        pcinspector_tasking
        Qt6::Core)
    set(allowed_pcinspector_app_ui
        pcinspector_app_config
        pcinspector_app_model
        pcinspector_app_session
        pcinspector_import_async
        pcinspector_platform
        pcinspector_pointcloud
        pcinspector_renderer_api
        pcinspector_scene
        pcinspector_vector
        Qt6::Concurrent
        Qt6::Widgets)
    set(allowed_pcinspector_renderer
        pcinspector_navigation
        pcinspector_platform
        pcinspector_pointcloud
        pcinspector_renderer_api
        pcinspector_renderer_planning
        pcinspector_scene
        pcinspector_vector
        Qt6::GuiPrivate
        Qt6::Widgets)
    set(allowed_pcinspector
        pcinspector_app_config
        pcinspector_app_ui
        pcinspector_development_support
        pcinspector_import_async
        pcinspector_import_gdal
        pcinspector_import_ogr
        pcinspector_import_pdal
        pcinspector_platform
        pcinspector_renderer
        Qt6::Core)

    set(manifest "# Generated by pci_register_architecture_checks.\n")
    string(APPEND manifest "set(PCI_ARCHITECTURE_TARGETS ${target_names})\n")
    foreach(target IN LISTS target_names)
        if(NOT TARGET "${target}")
            message(FATAL_ERROR "Architecture target '${target}' does not exist")
        endif()
        get_target_property(target_type "${target}" TYPE)
        if(target_type STREQUAL "INTERFACE_LIBRARY")
            get_target_property(link_items "${target}" INTERFACE_LINK_LIBRARIES)
        else()
            get_target_property(link_items "${target}" LINK_LIBRARIES)
        endif()
        if(NOT link_items)
            set(link_items "")
        endif()

        set(observed "")
        foreach(item IN LISTS link_items)
            # qt_add_executable appends platform-plugin selection expressions.
            # They are Qt implementation detail, not project-authored edges.
            if(item MATCHES "^\\$<" AND item MATCHES "QT_IS_PLUGIN_GENEX")
                continue()
            endif()
            pci_normalize_link_item(normalized "${item}")
            if(normalized MATCHES
                    "^pcinspector_(project_options|project_warnings)$")
                continue()
            endif()
            list(APPEND observed "${normalized}")
        endforeach()
        list(REMOVE_DUPLICATES observed)
        list(SORT observed)
        set(expected "")
        foreach(item IN LISTS allowed_${target})
            pci_normalize_link_item(normalized "${item}")
            list(APPEND expected "${normalized}")
        endforeach()
        if(APPLE AND target STREQUAL "pcinspector_platform")
            list(REMOVE_ITEM expected Psapi)
        elseif(NOT WIN32 AND target STREQUAL "pcinspector_platform")
            list(REMOVE_ITEM expected Psapi)
        endif()
        list(REMOVE_DUPLICATES expected)
        list(SORT expected)
        string(APPEND manifest
               "set(PCI_OBSERVED_${target} [==[${observed}]==])\n")
        string(APPEND manifest
               "set(PCI_EXPECTED_${target} [==[${expected}]==])\n")
    endforeach()

    set(manifest_path
        "${CMAKE_CURRENT_BINARY_DIR}/PciArchitectureTargets.cmake")
    file(WRITE "${manifest_path}" "${manifest}")

    add_test(NAME architecture_include_boundaries
        COMMAND "${CMAKE_COMMAND}"
                "-DPROJECT_SOURCE_DIR=${PROJECT_SOURCE_DIR}"
                -P "${PROJECT_SOURCE_DIR}/cmake/CheckIncludeBoundaries.cmake")
    add_test(NAME architecture_target_boundaries
        COMMAND "${CMAKE_COMMAND}"
                "-DMANIFEST=${manifest_path}"
                -P "${PROJECT_SOURCE_DIR}/cmake/CheckTargetBoundaries.cmake")
    set_tests_properties(
        architecture_include_boundaries architecture_target_boundaries
        PROPERTIES LABELS "architecture")
endfunction()
