# Compile every exported header with only its owning target's public dependencies.
get_property(pci_public_modules GLOBAL PROPERTY PCI_MODULE_TARGETS)
foreach(target IN LISTS pci_public_modules)
    string(REGEX REPLACE "^pcinspector_" "" module "${target}")
    get_target_property(include_roots ${target} INTERFACE_INCLUDE_DIRECTORIES)
    set(headers "")
    foreach(include_root IN LISTS include_roots)
        if(include_root MATCHES "/include$")
            file(GLOB_RECURSE exported CONFIGURE_DEPENDS RELATIVE "${include_root}" "${include_root}/*.h")
            list(APPEND headers ${exported})
        endif()
    endforeach()
    if(headers)
        pci_add_header_self_containment(${module} ${target} ${headers})
    endif()
endforeach()
pci_add_header_self_containment_target()
