function(pci_add_point_shaders target resource_name)
    if(NOT TARGET ${target})
        message(FATAL_ERROR
                "pci_add_point_shaders: unknown target '${target}'")
    endif()

    # Single build-system inventory for the point-render and pick shader ABI.
    # The application and native-GPU tests consume identical qsb packages.
    qt_add_shaders(${target} ${resource_name}
            PREFIX "/shaders"
            BASE "${PROJECT_SOURCE_DIR}/shaders"
            FILES
            "${PROJECT_SOURCE_DIR}/shaders/edl.vert"
            "${PROJECT_SOURCE_DIR}/shaders/edl.frag"
            "${PROJECT_SOURCE_DIR}/shaders/pick.vert"
            "${PROJECT_SOURCE_DIR}/shaders/pick.frag"
            "${PROJECT_SOURCE_DIR}/shaders/points.vert"
            "${PROJECT_SOURCE_DIR}/shaders/points.frag"
            "${PROJECT_SOURCE_DIR}/shaders/raster.vert"
            "${PROJECT_SOURCE_DIR}/shaders/raster.frag"
            "${PROJECT_SOURCE_DIR}/shaders/vector_fill.vert"
            "${PROJECT_SOURCE_DIR}/shaders/vector_fill.frag"
            "${PROJECT_SOURCE_DIR}/shaders/vector_line.vert"
            "${PROJECT_SOURCE_DIR}/shaders/vector_line.frag"
            "${PROJECT_SOURCE_DIR}/shaders/vector_marker.vert"
            "${PROJECT_SOURCE_DIR}/shaders/vector_marker.frag")

    # texelFetch is intentionally part of the Surface capability contract and
    # cannot be translated to the legacy GLSL 100/120 variants generated by
    # qt_add_shaders by default. Keep the other shaders broadly compatible,
    # while baking Surface only for APIs new enough to expose TexelFetch.
    qt_add_shaders(${target} ${resource_name}_surface
            PREFIX "/shaders"
            BASE "${PROJECT_SOURCE_DIR}/shaders"
            GLSL "310 es,330"
            FILES
            "${PROJECT_SOURCE_DIR}/shaders/raster_surface.vert"
            "${PROJECT_SOURCE_DIR}/shaders/raster_surface.frag")
endfunction()
